
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring:

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ssm_db
    password: asswecan
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource
