spring:
  application:
    name: redis
  redis:
    database: 0
    password: asswecan
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-idle: 4
        max-wait: 1ms
        min-idle: 0
    host: localhost